# Permalinks
permalink:        pretty

# Setup
url:              http://huytr.com

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:

title:            Huy Trinh

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  Can I be a cool nerd?

# The tags listed as entries in the sidebar
sidebar_tags:     [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:            https://source.unsplash.com/daily
color:            '#A85641'

author:
  name:           'Huy Trinh'
  twitter:        huypdtrinh
  github:         trinhphandinhhuy
  linkedin:       trinhphandinhhuy
  photo:          https://scontent-arn2-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/1914185_10201295546388479_6283399812864270986_n.jpg?oh=5b1bbde02941106313660f9541385831&oe=57BCB282

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Huy Trinh, a LAMK student trying to become a back-end developer someday.
