# Permalinks
permalink:        pretty

# Setup
url:              http://huytr.com

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:

title:            Huy Trinh

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  Can a nerd still be cool?

# The tags listed as entries in the sidebar
sidebar_tags:     [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:            https://source.unsplash.com/daily
color:            '#A85641'

author:
  name:           'Huy Trinh'
  twitter:        huypdtrinh
  github:         trinhphandinhhuy
  linkedin:       trinhphandinhhuy
  photo:          http://i.imgur.com/yU3hNi3.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about: |
    Huy Trinh was born in Vietnam 2 dozen years ago. He's about to stop referring to himself in a 3rd person, 'cause I'm wring this myself...
    Here's the fact - I'm just a normal student who was kind of lucky to know what my passion very soon, from the moment I joined Lahti UAS for studying BIT degree. 
    I wanted to be a web developer. I have been spending lots of my time making websites, especially web apps. Most of them are for university's projects, and the rest are my side/ hobby projects I made to fulfill some of my needs or for fun :D
    I am very keen on learning new techonologies to support my field. My favourite subjects at the moment are Docker and Continuous Delivery.  
    
    Beside coding, watching movies, especially TV shows is my favourite thing to do. I can binge-watch a whole season just for 2 or 3 days :P. I believe we can learn a lot from movie quotes.  
    I don't always have time and budget to travel but when I do, I try to visit many places as I can because I really enjoy seeing new things, meeting new people, trying new food and so on.  
    That's pretty much about me, thanks for reading ^^
    
    
  
  skill: |
    Back-end: 
      PHP / Node.js / Python |
      MySQL / MongoDB

    Cloud Services:
      Amazon Web Services (EC2, S3), Docker
      Git / Linux OS
      
    Front-end:
      Javascript, AngularJS, jQuery
      
    
  contact: |
    Email: me@huytr.com / trinhphandinhhuy@gmail.com  
    Phone: (+358) 466 33 0148  
    
    
